# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
RSpec.configure do |config|
  config.treat_symbols_as_metadata_keys_with_true_values = true
  config.run_all_when_everything_filtered = true
  config.filter_run :focus

  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  config.order = 'random'
end

require 'rubygems'
require 'grok-pure'
require 'rspec'

RSpec::Matchers.define :have_logstash_field do |field|
  chain :with_value do |value|
    @value= value
  end

  match do |grok_match|
    grok_captures = grok_match.captures()
    grok_field = grok_captures.keys.grep(/.*:#{field}$/)
    if @value
      grok_captures[grok_field.first].first.should == @value
    else
      grok_field.size.should equal 1
    end
  end

  failure_message_for_should do |grok_match|
    if @value
      "\"#{field}\" isn't set to \"#{@value}\" in #{grok_match.captures()}"
    else
      "\"#{field}\" suffix not present in #{grok_match.captures().keys}"
    end
  end
end
